### ISSUE TITLE
Could you add values to mode slider?

### ISSUE THREAD

**Issue by Suzuki-Re** [lewloiwc/JSFX-for-ReaRack#1]
Hi, thanks for the useful JSFXs. I like your math_exp_26 Texture Mode 0.1.1 too. 

This is not an issue per se.

Could you possibly add  the minimum value, maximum value, and change increment to the mode sliders? The mode slider which I mean here is switch-selectable ones.

Yes, I can add it by myself, but it would be handy if it's implemented in the first place since the script like FX Devices allows users to create UI for plugins and in order to make exposed parameters work properly in the script, those values in the above need to be set.

Sorry if my suggestion does not make sense. Thanks for considering it!

**Comment by lewloiwc** [comment]
I have added the values!
I've reviewed it several times and I think it's ok, but if you notice that the added values are incorrect, please let me know!

Translated with [www.DeepL.com/Translator](http://www.deepl.com/Translator) (free version)

**Comment by Suzuki-Re** [comment]
Thanks!
